apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-docker
  namespace: drone-runner-docker
spec:
  values:
    image:
      ## https://hub.docker.com/r/drone/drone-runner-docker/tags?page=1
      ## https://github.com/drone/charts/blob/master/charts/drone-runner-docker/values.yaml
      tag: "1.8"
    dind:
      commandArgs:
        - --host
        - tcp://localhost:2375
        - --mtu=1450
    extraSecretNamesForEnvFrom:
      - my-drone-secrets
    env:
      DRONE_RPC_HOST: drone.pekware.club
      DRONE_RPC_PROTO: https
      DRONE_RUNNER_NETWORK_OPTS: com.docker.network.driver.mtu:1450
