apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: drone-runner-docker
  namespace: drone-runner-docker
resources:
  - ../../base/drone-runner-docker/
  - sealed.secret.drone.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
