apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
