apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    replicaCount: 2
    strategy:
      type: RollingUpdate
    clusterDomain: gitea.home.pekware.club
    image:
      repository: gitea/gitea
      # https://github.com/go-gitea/gitea/releases
      # https://gitea.com/gitea/helm-chart/src/branch/main/Chart.yaml
      tag: 1.23.8
      pullPolicy: IfNotPresent
      rootless: true
    service:
      ssh:
        port: 222
    ingress:
      apiVersion: networking.k8s.io/v1
      enabled: true
      hosts:
        - host: gitea.home.pekware.club
          paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
          - gitea.home.pekware.club
    persistence:
      enabled: true
      create: false
      claimName: gitea
      accessModes:
        - ReadWriteMany
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        passwordMode: initialOnlyNoReset
        email: king.phil@gmail.com
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-extra-secrets
              key: database_password
        - name: GITEA__SESSION__PROVIDER_CONFIG
          valueFrom:
            secretKeyRef:
              name: gitea-extra-secrets
              key: session_provider_config
      ## https://docs.gitea.com/administration/config-cheat-sheet
      config:
        database:
          ## https://docs.gitea.com/installation/database-prep
          DB_TYPE: mysql
          HOST: mariadb
          NAME: giteadb
          USER: gitea
          ## note: PASSWD in "extra secrets" above
          #SCHEMA: gitea
        session:
          PROVIDER: redis
          ## note: PROVIDER_CONFIG in "extra secrets" above
        cache:
          ADAPTER: memory
        queue:
          TYPE: channel
        webhook:
          ALLOWED_HOST_LIST: '*'
        RUN_MODE: prod
        APP_NAME: 'Gitea: Git with a cup of tea'
        repository:
          DEFAULT_BRANCH: main
          ENABLE_PUSH_CREATE_ORG: true
          DEFAULT_PRIVATE: private
        server:
          SSH_PORT: 222
          ROOT_URL: https://gitea.home.pekware.club
          PROTOCOL: http
          DOMAIN: gitea.home.pekware.club
    actions:
      enabled: true
      statefulset:
        actRunner:
          config: |
            log:
              level: info
            cache:
              enabled: true
            runner:
              capacity: 4
              # https://gitea.com/gitea/act_runner/src/branch/main/internal/app/cmd/register.go#L93
              # https://hub.docker.com/r/gitea/runner-images/tags
              labels:
                - "act-latest:docker://gitea/runner-images:ubuntu-latest"
                - "act-latest-slim:docker://gitea/runner-images:ubuntu-latest-slim"
      existingSecret: gitea-admin-secret
      existingSecretKey: token
    mysql:
      enabled: false
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    test:
      enabled: false
