---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAk5SqW88Lt0bF64YQjDiQPUUZDTGwIM3tDFREmjmg3ViHeOt+VEEXp08HuzvkDXFIqKT2Cxj5Jn6vVoRV0PQ0WgyTC2jVFeHl35j71zMlE43kiXCD/S17kln5jgUMzmTFtNVrlPu5fvdW3YTEgUflp6l9lDh5spKE+RJas9qZ5sowht/fXtwwrrsMHiDSugZx4MyRJuqXrEWCEAgXWC0DH90dirMBwrJpVyDmzdVH+NMN6nopC7oZh0wz2A+P5L0UC78+ZOVZqrKs/KiHOyERSh4I1IYcNvatChVg9qHFkVFLxbQ/kBO7Mhgd1ix132oRkPYmygvSZKwpkPgNU53SfX1HfVa0TMm5Q3Oy6DIhT8f9EubugmDIgtXcnaaQMtVjO4JyIr1ysASUZqyzQ2kFUQSV/BjFsS7+AUVuVSgElN5QGoe9xufGGi5ZQXvbtS7+iU3/fuAISssAmbQiVtU24+ypUjbhxP9v+zb9ZPdPG32sK7qacIiJBR+ywU4srcBkT6MHAT9A6VnoIcxgMQZrbOZaDOVKZQFdIbIV/2ASLKrU/M2MPR7lEPIMq6zIl7wt8hDn0Y9U0F3fPba1T4AEHwoHs8kbsRTEhoGhP+1QDfxENXzgi0K1ePpgGwYgK+K0C+dnCI44S7Ct1fBrrNBPu899uNtE019mlB9M1ZbounoZqpeICsWOzLPASaYyZsSujEyPS0v0jE3BPNJL13/gedbC4yeTXOgU4eVEhvNigwA==
    username: AgBjE9AcAOH/JmryCGdh1MJiWSN4YKbyCSabg1Zd9RKBda7weW0A0/Q39JqLfqkAI8u/6p+dKpNMFHmG4WhDyDc6O12Ws6qX7OAT0gkV9KCH6X5d5x7zAfGZ+7qpP5M+AdwpHyxNQ8hQ1bwNmz5zjty9aWBvX/IWF43rcnvWT/yOUUzBam76ac0ycEFMTYfanVu0Y3w2EPJdnIUEYbq0aATYGQnuWgug2WrUoJfoT5bJg1Fmx8+x3ZexZQcTubO9xyx5FXCcfPqwOasVBb4vMWq/yw/Kbc9yh6X1dwRcLVmpT8mOsdZzuVgYWnj7RLWHkK1zLtwJlQ5QlxD/13AlBDHQPLAcEQTLsPmqvI1Q6qRZFw5HSQkqyXXeD05A7ubEIxub7lhqib1YeHwLLNfcV8zW+H2FtoDwbARZtDHCaVvHp5wiLq9isrBpO7xzFnpPdOUHbn9TS1WOKN4zzsHWYbShx1gijKBiEJLi/MeJniyRzKGzR1n+cYE+5wTF0SQBNdyXQQdYfucuZhr1NtzNxBeSL1Ffsr4lcTVDBiiKdEiaWfNdAcg7A0JmBZGIEdTVaguN5lT0ECht+p8oW2Y2DQW1gy+gg7OCmxoyxp1IbhqXENIRieH1V7GJ/ylxkHhYsPdSAUIDo7Fam/ldgMItfvv+8kd1w2TMd8q27bNdqHPg22Zz4qtORIsrKD2GHUwB5qmCdkqAKGkhHfE=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
