apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-prod.star.home.pekware.club
  namespace: cert-manager
spec:
  secretName: acme-prod.star.home.pekware.club
  issuerRef:
    name: letsencrypt-pekware
    kind: ClusterIssuer
  commonName: 'home.pekware.club'
  dnsNames:
  - "home.pekware.club"
  - "*.home.pekware.club"
