apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: codemonkeys.site
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: king.phil@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: codemonkeys.site
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
      selector:
        dnsZones:
          - "codemonkeys.site"
