apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
  - sealed.secret.do-token.yaml
  - clusterissuer-home-pekware-club.yaml
  - certificate-home-pekware-club.yaml
  #- clusterissuer.codemonkeys.site.yaml
  #- certificate.codemonkeys.site.yaml
