apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: drone
  namespace: drone
resources:
  - ../../base/drone/
  - sealed.secret.drone.yaml
  - pvc.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
