apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone
  namespace: drone
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
