apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  values:
    image:
      repository: drone/drone
      # https://hub.docker.com/r/drone/drone/tags
      tag: "2.24"
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      hosts:
        - host: drone.home.pekware.club
          paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
          - drone.home.pekware.club
    persistentVolume:
      existingClaim: drone

    # https://docs.drone.io/server/provider/gitea/
    env:
      DRONE_SERVER_HOST: drone.home.pekware.club
      DRONE_SERVER_PROTO: https
      DRONE_GITEA_SERVER: https://gitea.home.pekware.club
      DRONE_USER_CREATE: username:king.phil,admin:true
    extraSecretNamesForEnvFrom:
      - my-drone-secrets
