---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: podinfo
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 6.2.x
