apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  install:
    remediation:
      retries: 3
  interval: 2h
  chart:
    spec:
      chart: gitea
      # https://gitea.com/gitea/helm-chart/tags
      version: 10.x
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      interval: 2h
