---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  chart:
    # https://github.com/actions/actions-runner-controller
    spec:
      chart: charts/gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: gha-runner-controller
        namespace: gha-runner-controller
      version: 0.9.x
  interval: 2h0m0s
  values:
    githubConfigUrl: "https://github.com/pekware"
    githubConfigSecret: pre-defined-secret
    minRunners: 1
    containerMode:
      type: dind
