---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  chart:
    # https://github.com/actions/actions-runner-controller
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc-runners
        namespace: arc-runners
      version: 0.10.0
  interval: 2h0m0s
  values:
    githubConfigUrl: "https://github.com/pekware"
    githubConfigSecret: pre-defined-secret
    minRunners: 1
    maxRunners: 10
    containerMode:
      type: dind
