---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gha-runner-controller
  namespace: gha-runner-controller
spec:
  chart:
    # https://github.com/actions/actions-runner-controller
    spec:
      chart: gha-runner-scale-set-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gha-runner-controller
        namespace: gha-runner-controller
      version: 0.10.0
  interval: 2h0m0s
