apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    replicaCount: 1
    strategy:
      type: RollingUpdate
    clusterDomain: gitea.development.pekware.club
    image:
      repository: gitea/gitea
      # https://github.com/go-gitea/gitea/releases
      # https://gitea.com/gitea/helm-chart/src/branch/main/Chart.yaml
      tag: 1.22.3
      pullPolicy: IfNotPresent
      rootless: true
    service:
      ssh:
        port: 222
    ingress:
      enabled: true
      hosts:
        - host: gitea.development.pekware.club
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.development.pekware.club
    persistence:
      enabled: true
      create: false
      claimName: gitea
      accessModes:
        - ReadWriteMany
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        email: king.phil@gmail.com
      ## https://docs.gitea.com/administration/config-cheat-sheet
      config:
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: channel
        webhook:
          ALLOWED_HOST_LIST: '*'
        RUN_MODE: dev
        APP_NAME: "Gitea (development): Git with a cup of tea"
        repository:
          DEFAULT_BRANCH: main
          ENABLE_PUSH_CREATE_ORG: true
          DEFAULT_PRIVATE: private
        server:
          SSH_PORT: 222
          ROOT_URL: https://gitea.development.pekware.club
          PROTOCOL: http
          DOMAIN: gitea.development.pekware.club
    mysql:
      enabled: false

    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
